package com.tiendas3b.almacen.db.dao;

import com.tiendas3b.almacen.db.dao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "ARTICLE_RESEARCH".
 */
public class ArticleResearch extends EqualsBase  {

    private Long id;
    private Integer avgPed;
    private Integer avgFzd;
    private Integer avgSurt;
    private Integer avgSo;
    private Integer avgInvest;
    private Integer avgCancel;
    private long regionId;
    private long storeId;
    /** Not-null value. */
    private String date;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient ArticleResearchDao myDao;

    private Region region;
    private Long region__resolvedKey;

    private Store store;
    private Long store__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ArticleResearch() {
    }

    public ArticleResearch(Long id) {
        this.id = id;
    }

    public ArticleResearch(Long id, Integer avgPed, Integer avgFzd, Integer avgSurt, Integer avgSo, Integer avgInvest, Integer avgCancel, long regionId, long storeId, String date) {
        this.id = id;
        this.avgPed = avgPed;
        this.avgFzd = avgFzd;
        this.avgSurt = avgSurt;
        this.avgSo = avgSo;
        this.avgInvest = avgInvest;
        this.avgCancel = avgCancel;
        this.regionId = regionId;
        this.storeId = storeId;
        this.date = date;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getArticleResearchDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getAvgPed() {
        return avgPed;
    }

    public void setAvgPed(Integer avgPed) {
        this.avgPed = avgPed;
    }

    public Integer getAvgFzd() {
        return avgFzd;
    }

    public void setAvgFzd(Integer avgFzd) {
        this.avgFzd = avgFzd;
    }

    public Integer getAvgSurt() {
        return avgSurt;
    }

    public void setAvgSurt(Integer avgSurt) {
        this.avgSurt = avgSurt;
    }

    public Integer getAvgSo() {
        return avgSo;
    }

    public void setAvgSo(Integer avgSo) {
        this.avgSo = avgSo;
    }

    public Integer getAvgInvest() {
        return avgInvest;
    }

    public void setAvgInvest(Integer avgInvest) {
        this.avgInvest = avgInvest;
    }

    public Integer getAvgCancel() {
        return avgCancel;
    }

    public void setAvgCancel(Integer avgCancel) {
        this.avgCancel = avgCancel;
    }

    public long getRegionId() {
        return regionId;
    }

    public void setRegionId(long regionId) {
        this.regionId = regionId;
    }

    public long getStoreId() {
        return storeId;
    }

    public void setStoreId(long storeId) {
        this.storeId = storeId;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    /** To-one relationship, resolved on first access. */
    public Region getRegion() {
        long __key = this.regionId;
        if (region__resolvedKey == null || !region__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            RegionDao targetDao = daoSession.getRegionDao();
            Region regionNew = targetDao.load(__key);
            synchronized (this) {
                region = regionNew;
            	region__resolvedKey = __key;
            }
        }
        return region;
    }

    public void setRegion(Region region) {
        if (region == null) {
            throw new DaoException("To-one property 'regionId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.region = region;
            regionId = region.getId();
            region__resolvedKey = regionId;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Store getStore() {
        long __key = this.storeId;
        if (store__resolvedKey == null || !store__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            StoreDao targetDao = daoSession.getStoreDao();
            Store storeNew = targetDao.load(__key);
            synchronized (this) {
                store = storeNew;
            	store__resolvedKey = __key;
            }
        }
        return store;
    }

    public void setStore(Store store) {
        if (store == null) {
            throw new DaoException("To-one property 'storeId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.store = store;
            storeId = store.getId();
            store__resolvedKey = storeId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
