package com.tiendas3b.almacen.db.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.tiendas3b.almacen.db.dao.ArticleResearch;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ARTICLE_RESEARCH".
*/
public class ArticleResearchDao extends AbstractDao<ArticleResearch, Long> {

    public static final String TABLENAME = "ARTICLE_RESEARCH";

    /**
     * Properties of entity ArticleResearch.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property AvgPed = new Property(1, Integer.class, "avgPed", false, "AVG_PED");
        public final static Property AvgFzd = new Property(2, Integer.class, "avgFzd", false, "AVG_FZD");
        public final static Property AvgSurt = new Property(3, Integer.class, "avgSurt", false, "AVG_SURT");
        public final static Property AvgSo = new Property(4, Integer.class, "avgSo", false, "AVG_SO");
        public final static Property AvgInvest = new Property(5, Integer.class, "avgInvest", false, "AVG_INVEST");
        public final static Property AvgCancel = new Property(6, Integer.class, "avgCancel", false, "AVG_CANCEL");
        public final static Property RegionId = new Property(7, long.class, "regionId", false, "REGION_ID");
        public final static Property StoreId = new Property(8, long.class, "storeId", false, "STORE_ID");
        public final static Property Date = new Property(9, String.class, "date", false, "DATE");
    };

    private DaoSession daoSession;


    public ArticleResearchDao(DaoConfig config) {
        super(config);
    }
    
    public ArticleResearchDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ARTICLE_RESEARCH\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"AVG_PED\" INTEGER," + // 1: avgPed
                "\"AVG_FZD\" INTEGER," + // 2: avgFzd
                "\"AVG_SURT\" INTEGER," + // 3: avgSurt
                "\"AVG_SO\" INTEGER," + // 4: avgSo
                "\"AVG_INVEST\" INTEGER," + // 5: avgInvest
                "\"AVG_CANCEL\" INTEGER," + // 6: avgCancel
                "\"REGION_ID\" INTEGER NOT NULL ," + // 7: regionId
                "\"STORE_ID\" INTEGER NOT NULL ," + // 8: storeId
                "\"DATE\" TEXT NOT NULL );"); // 9: date
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_ARTICLE_RESEARCH_REGION_ID_STORE_ID_DATE ON ARTICLE_RESEARCH" +
                " (\"REGION_ID\",\"STORE_ID\",\"DATE\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ARTICLE_RESEARCH\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ArticleResearch entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer avgPed = entity.getAvgPed();
        if (avgPed != null) {
            stmt.bindLong(2, avgPed);
        }
 
        Integer avgFzd = entity.getAvgFzd();
        if (avgFzd != null) {
            stmt.bindLong(3, avgFzd);
        }
 
        Integer avgSurt = entity.getAvgSurt();
        if (avgSurt != null) {
            stmt.bindLong(4, avgSurt);
        }
 
        Integer avgSo = entity.getAvgSo();
        if (avgSo != null) {
            stmt.bindLong(5, avgSo);
        }
 
        Integer avgInvest = entity.getAvgInvest();
        if (avgInvest != null) {
            stmt.bindLong(6, avgInvest);
        }
 
        Integer avgCancel = entity.getAvgCancel();
        if (avgCancel != null) {
            stmt.bindLong(7, avgCancel);
        }
        stmt.bindLong(8, entity.getRegionId());
        stmt.bindLong(9, entity.getStoreId());
        stmt.bindString(10, entity.getDate());
    }

    @Override
    protected void attachEntity(ArticleResearch entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ArticleResearch readEntity(Cursor cursor, int offset) {
        ArticleResearch entity = new ArticleResearch( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // avgPed
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // avgFzd
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // avgSurt
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // avgSo
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // avgInvest
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // avgCancel
            cursor.getLong(offset + 7), // regionId
            cursor.getLong(offset + 8), // storeId
            cursor.getString(offset + 9) // date
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ArticleResearch entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAvgPed(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setAvgFzd(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setAvgSurt(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setAvgSo(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setAvgInvest(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setAvgCancel(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setRegionId(cursor.getLong(offset + 7));
        entity.setStoreId(cursor.getLong(offset + 8));
        entity.setDate(cursor.getString(offset + 9));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ArticleResearch entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ArticleResearch entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getRegionDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getStoreDao().getAllColumns());
            builder.append(" FROM ARTICLE_RESEARCH T");
            builder.append(" LEFT JOIN REGION T0 ON T.\"REGION_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN STORE T1 ON T.\"STORE_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected ArticleResearch loadCurrentDeep(Cursor cursor, boolean lock) {
        ArticleResearch entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Region region = loadCurrentOther(daoSession.getRegionDao(), cursor, offset);
         if(region != null) {
            entity.setRegion(region);
        }
        offset += daoSession.getRegionDao().getAllColumns().length;

        Store store = loadCurrentOther(daoSession.getStoreDao(), cursor, offset);
         if(store != null) {
            entity.setStore(store);
        }

        return entity;    
    }

    public ArticleResearch loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<ArticleResearch> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<ArticleResearch> list = new ArrayList<ArticleResearch>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<ArticleResearch> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<ArticleResearch> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
