package com.tiendas3b.almacen.db.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.tiendas3b.almacen.db.dao.Buy;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BUY".
*/
public class BuyDao extends AbstractDao<Buy, Long> {

    public static final String TABLENAME = "BUY";

    /**
     * Properties of entity Buy.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Total = new Property(1, Double.class, "total", false, "TOTAL");
        public final static Property ProgramedDate = new Property(2, java.util.Date.class, "programedDate", false, "PROGRAMED_DATE");
        public final static Property Platform = new Property(3, Integer.class, "platform", false, "PLATFORM");
        public final static Property Time = new Property(4, String.class, "time", false, "TIME");
        public final static Property Express = new Property(5, Boolean.class, "express", false, "EXPRESS");
        public final static Property DeliveryTime = new Property(6, String.class, "deliveryTime", false, "DELIVERY_TIME");
        public final static Property Checked = new Property(7, int.class, "checked", false, "CHECKED");
        public final static Property RegionId = new Property(8, long.class, "regionId", false, "REGION_ID");
        public final static Property ProviderId = new Property(9, long.class, "providerId", false, "PROVIDER_ID");
        public final static Property Folio = new Property(10, int.class, "folio", false, "FOLIO");
        public final static Property Mov = new Property(11, String.class, "mov", false, "MOV");
        public final static Property Forced = new Property(12, int.class, "forced", false, "FORCED");
    };

    private DaoSession daoSession;


    public BuyDao(DaoConfig config) {
        super(config);
    }
    
    public BuyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BUY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TOTAL\" REAL," + // 1: total
                "\"PROGRAMED_DATE\" INTEGER," + // 2: programedDate
                "\"PLATFORM\" INTEGER," + // 3: platform
                "\"TIME\" TEXT," + // 4: time
                "\"EXPRESS\" INTEGER," + // 5: express
                "\"DELIVERY_TIME\" TEXT," + // 6: deliveryTime
                "\"CHECKED\" INTEGER NOT NULL ," + // 7: checked
                "\"REGION_ID\" INTEGER NOT NULL ," + // 8: regionId
                "\"PROVIDER_ID\" INTEGER NOT NULL ," + // 9: providerId
                "\"FOLIO\" INTEGER NOT NULL ," + // 10: folio
                "\"MOV\" TEXT NOT NULL ," + // 11: mov
                "\"FORCED\" INTEGER NOT NULL );"); // 12: forced
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_BUY_REGION_ID_PROVIDER_ID_FOLIO_MOV_FORCED ON BUY" +
                " (\"REGION_ID\",\"PROVIDER_ID\",\"FOLIO\",\"MOV\",\"FORCED\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BUY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Buy entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Double total = entity.getTotal();
        if (total != null) {
            stmt.bindDouble(2, total);
        }
 
        java.util.Date programedDate = entity.getProgramedDate();
        if (programedDate != null) {
            stmt.bindLong(3, programedDate.getTime());
        }
 
        Integer platform = entity.getPlatform();
        if (platform != null) {
            stmt.bindLong(4, platform);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(5, time);
        }
 
        Boolean express = entity.getExpress();
        if (express != null) {
            stmt.bindLong(6, express ? 1L: 0L);
        }
 
        String deliveryTime = entity.getDeliveryTime();
        if (deliveryTime != null) {
            stmt.bindString(7, deliveryTime);
        }
        stmt.bindLong(8, entity.getChecked());
        stmt.bindLong(9, entity.getRegionId());
        stmt.bindLong(10, entity.getProviderId());
        stmt.bindLong(11, entity.getFolio());
        stmt.bindString(12, entity.getMov());
        stmt.bindLong(13, entity.getForced());
    }

    @Override
    protected void attachEntity(Buy entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Buy readEntity(Cursor cursor, int offset) {
        Buy entity = new Buy( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getDouble(offset + 1), // total
            cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // programedDate
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // platform
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // time
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0, // express
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // deliveryTime
            cursor.getInt(offset + 7), // checked
            cursor.getLong(offset + 8), // regionId
            cursor.getLong(offset + 9), // providerId
            cursor.getInt(offset + 10), // folio
            cursor.getString(offset + 11), // mov
            cursor.getInt(offset + 12) // forced
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Buy entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTotal(cursor.isNull(offset + 1) ? null : cursor.getDouble(offset + 1));
        entity.setProgramedDate(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setPlatform(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setTime(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setExpress(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
        entity.setDeliveryTime(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setChecked(cursor.getInt(offset + 7));
        entity.setRegionId(cursor.getLong(offset + 8));
        entity.setProviderId(cursor.getLong(offset + 9));
        entity.setFolio(cursor.getInt(offset + 10));
        entity.setMov(cursor.getString(offset + 11));
        entity.setForced(cursor.getInt(offset + 12));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Buy entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Buy entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getRegionDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getProviderDao().getAllColumns());
            builder.append(" FROM BUY T");
            builder.append(" LEFT JOIN REGION T0 ON T.\"REGION_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN PROVIDER T1 ON T.\"PROVIDER_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Buy loadCurrentDeep(Cursor cursor, boolean lock) {
        Buy entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Region region = loadCurrentOther(daoSession.getRegionDao(), cursor, offset);
         if(region != null) {
            entity.setRegion(region);
        }
        offset += daoSession.getRegionDao().getAllColumns().length;

        Provider provider = loadCurrentOther(daoSession.getProviderDao(), cursor, offset);
         if(provider != null) {
            entity.setProvider(provider);
        }

        return entity;    
    }

    public Buy loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Buy> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Buy> list = new ArrayList<Buy>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Buy> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Buy> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
