package com.tiendas3b.almacen.db.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "DRIVER".
 */
public class Driver extends SpinnerBase  {

    private Long id;
    private String description;
    private Integer active;
    private long regionId;
    private long driverId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Driver() {
    }

    public Driver(Long id) {
        this.id = id;
    }

    public Driver(Long id, String description, Integer active, long regionId, long driverId) {
        this.id = id;
        this.description = description;
        this.active = active;
        this.regionId = regionId;
        this.driverId = driverId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getActive() {
        return active;
    }

    public void setActive(Integer active) {
        this.active = active;
    }

    public long getRegionId() {
        return regionId;
    }

    public void setRegionId(long regionId) {
        this.regionId = regionId;
    }

    public long getDriverId() {
        return driverId;
    }

    public void setDriverId(long driverId) {
        this.driverId = driverId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
