package com.tiendas3b.almacen.db.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "EPACKAGE_DOWNLOAD".
 */
public class EpackageDownload extends EqualsBase  {

    private Long id;
    private Integer activo;
    private Integer statusLeave;
    private Integer tarjetStatus;
    private String fecha;
    private long almacen;
    private long camClave;
    private long packageId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public EpackageDownload() {
    }

    public EpackageDownload(Long id) {
        this.id = id;
    }

    public EpackageDownload(Long id, Integer activo, Integer statusLeave, Integer tarjetStatus, String fecha, long almacen, long camClave, long packageId) {
        this.id = id;
        this.activo = activo;
        this.statusLeave = statusLeave;
        this.tarjetStatus = tarjetStatus;
        this.fecha = fecha;
        this.almacen = almacen;
        this.camClave = camClave;
        this.packageId = packageId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getActivo() {
        return activo;
    }

    public void setActivo(Integer activo) {
        this.activo = activo;
    }

    public Integer getStatusLeave() {
        return statusLeave;
    }

    public void setStatusLeave(Integer statusLeave) {
        this.statusLeave = statusLeave;
    }

    public Integer getTarjetStatus() {
        return tarjetStatus;
    }

    public void setTarjetStatus(Integer tarjetStatus) {
        this.tarjetStatus = tarjetStatus;
    }

    public String getFecha() {
        return fecha;
    }

    public void setFecha(String fecha) {
        this.fecha = fecha;
    }

    public long getAlmacen() {
        return almacen;
    }

    public void setAlmacen(long almacen) {
        this.almacen = almacen;
    }

    public long getCamClave() {
        return camClave;
    }

    public void setCamClave(long camClave) {
        this.camClave = camClave;
    }

    public long getPackageId() {
        return packageId;
    }

    public void setPackageId(long packageId) {
        this.packageId = packageId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
