package com.tiendas3b.almacen.db.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "ORDER_TYPE".
 */
public class OrderType extends SpinnerBase  {

    private Long id;
    private int typeId;
    private String description;
    private String alias;
    private long regionId;
    private Integer circuitId;
    private Boolean separate;
    private Boolean active;
    private Boolean scannerAvailable;
    private Boolean mobileAvailable;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public OrderType() {
    }

    public OrderType(Long id) {
        this.id = id;
    }

    public OrderType(Long id, int typeId, String description, String alias, long regionId, Integer circuitId, Boolean separate, Boolean active, Boolean scannerAvailable, Boolean mobileAvailable) {
        this.id = id;
        this.typeId = typeId;
        this.description = description;
        this.alias = alias;
        this.regionId = regionId;
        this.circuitId = circuitId;
        this.separate = separate;
        this.active = active;
        this.scannerAvailable = scannerAvailable;
        this.mobileAvailable = mobileAvailable;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getTypeId() {
        return typeId;
    }

    public void setTypeId(int typeId) {
        this.typeId = typeId;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getAlias() {
        return alias;
    }

    public void setAlias(String alias) {
        this.alias = alias;
    }

    public long getRegionId() {
        return regionId;
    }

    public void setRegionId(long regionId) {
        this.regionId = regionId;
    }

    public Integer getCircuitId() {
        return circuitId;
    }

    public void setCircuitId(Integer circuitId) {
        this.circuitId = circuitId;
    }

    public Boolean getSeparate() {
        return separate;
    }

    public void setSeparate(Boolean separate) {
        this.separate = separate;
    }

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public Boolean getScannerAvailable() {
        return scannerAvailable;
    }

    public void setScannerAvailable(Boolean scannerAvailable) {
        this.scannerAvailable = scannerAvailable;
    }

    public Boolean getMobileAvailable() {
        return mobileAvailable;
    }

    public void setMobileAvailable(Boolean mobileAvailable) {
        this.mobileAvailable = mobileAvailable;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
