package com.tiendas3b.almacen.db.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "QUESTION_ANSWER".
 */
public class QuestionAnswer {

    private long questionId;
    private long answerId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public QuestionAnswer() {
    }

    public QuestionAnswer(long questionId, long answerId) {
        this.questionId = questionId;
        this.answerId = answerId;
    }

    public long getQuestionId() {
        return questionId;
    }

    public void setQuestionId(long questionId) {
        this.questionId = questionId;
    }

    public long getAnswerId() {
        return answerId;
    }

    public void setAnswerId(long answerId) {
        this.answerId = answerId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
