package com.tiendas3b.almacen.db.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.tiendas3b.almacen.db.dao.Rack;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RACK".
*/
public class RackDao extends AbstractDao<Rack, Long> {

    public static final String TABLENAME = "RACK";

    /**
     * Properties of entity Rack.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RackId = new Property(1, long.class, "rackId", false, "RACK_ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property QuantityLevels = new Property(3, Integer.class, "quantityLevels", false, "QUANTITY_LEVELS");
        public final static Property AreaId = new Property(4, long.class, "areaId", false, "AREA_ID");
    };

    private DaoSession daoSession;

    private Query<Rack> area_RacksQuery;

    public RackDao(DaoConfig config) {
        super(config);
    }
    
    public RackDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RACK\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"RACK_ID\" INTEGER NOT NULL ," + // 1: rackId
                "\"NAME\" TEXT," + // 2: name
                "\"QUANTITY_LEVELS\" INTEGER," + // 3: quantityLevels
                "\"AREA_ID\" INTEGER NOT NULL );"); // 4: areaId
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_RACK_RACK_ID_AREA_ID ON RACK" +
                " (\"RACK_ID\",\"AREA_ID\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RACK\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Rack entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getRackId());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        Integer quantityLevels = entity.getQuantityLevels();
        if (quantityLevels != null) {
            stmt.bindLong(4, quantityLevels);
        }
        stmt.bindLong(5, entity.getAreaId());
    }

    @Override
    protected void attachEntity(Rack entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Rack readEntity(Cursor cursor, int offset) {
        Rack entity = new Rack( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // rackId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // quantityLevels
            cursor.getLong(offset + 4) // areaId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Rack entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRackId(cursor.getLong(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setQuantityLevels(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setAreaId(cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Rack entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Rack entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "racks" to-many relationship of Area. */
    public List<Rack> _queryArea_Racks(long areaId) {
        synchronized (this) {
            if (area_RacksQuery == null) {
                QueryBuilder<Rack> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.AreaId.eq(null));
                area_RacksQuery = queryBuilder.build();
            }
        }
        Query<Rack> query = area_RacksQuery.forCurrentThread();
        query.setParameter(0, areaId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getAreaDao().getAllColumns());
            builder.append(" FROM RACK T");
            builder.append(" LEFT JOIN AREA T0 ON T.\"AREA_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Rack loadCurrentDeep(Cursor cursor, boolean lock) {
        Rack entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Area area = loadCurrentOther(daoSession.getAreaDao(), cursor, offset);
         if(area != null) {
            entity.setArea(area);
        }

        return entity;    
    }

    public Rack loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Rack> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Rack> list = new ArrayList<Rack>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Rack> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Rack> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
