package com.tiendas3b.almacen.db.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.tiendas3b.almacen.db.dao.RackLevel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RACK_LEVEL".
*/
public class RackLevelDao extends AbstractDao<RackLevel, Long> {

    public static final String TABLENAME = "RACK_LEVEL";

    /**
     * Properties of entity RackLevel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property LevelId = new Property(1, long.class, "levelId", false, "LEVEL_ID");
        public final static Property Length = new Property(2, Float.class, "length", false, "LENGTH");
        public final static Property AvailableLength = new Property(3, Float.class, "availableLength", false, "AVAILABLE_LENGTH");
        public final static Property RackId = new Property(4, long.class, "rackId", false, "RACK_ID");
    };

    private DaoSession daoSession;

    private Query<RackLevel> rack_LevelsQuery;

    public RackLevelDao(DaoConfig config) {
        super(config);
    }
    
    public RackLevelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RACK_LEVEL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"LEVEL_ID\" INTEGER NOT NULL ," + // 1: levelId
                "\"LENGTH\" REAL," + // 2: length
                "\"AVAILABLE_LENGTH\" REAL," + // 3: availableLength
                "\"RACK_ID\" INTEGER NOT NULL );"); // 4: rackId
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_RACK_LEVEL_LEVEL_ID_RACK_ID ON RACK_LEVEL" +
                " (\"LEVEL_ID\",\"RACK_ID\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RACK_LEVEL\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, RackLevel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getLevelId());
 
        Float length = entity.getLength();
        if (length != null) {
            stmt.bindDouble(3, length);
        }
 
        Float availableLength = entity.getAvailableLength();
        if (availableLength != null) {
            stmt.bindDouble(4, availableLength);
        }
        stmt.bindLong(5, entity.getRackId());
    }

    @Override
    protected void attachEntity(RackLevel entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public RackLevel readEntity(Cursor cursor, int offset) {
        RackLevel entity = new RackLevel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // levelId
            cursor.isNull(offset + 2) ? null : cursor.getFloat(offset + 2), // length
            cursor.isNull(offset + 3) ? null : cursor.getFloat(offset + 3), // availableLength
            cursor.getLong(offset + 4) // rackId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, RackLevel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLevelId(cursor.getLong(offset + 1));
        entity.setLength(cursor.isNull(offset + 2) ? null : cursor.getFloat(offset + 2));
        entity.setAvailableLength(cursor.isNull(offset + 3) ? null : cursor.getFloat(offset + 3));
        entity.setRackId(cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(RackLevel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(RackLevel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "levels" to-many relationship of Rack. */
    public List<RackLevel> _queryRack_Levels(long rackId) {
        synchronized (this) {
            if (rack_LevelsQuery == null) {
                QueryBuilder<RackLevel> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.RackId.eq(null));
                rack_LevelsQuery = queryBuilder.build();
            }
        }
        Query<RackLevel> query = rack_LevelsQuery.forCurrentThread();
        query.setParameter(0, rackId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getRackDao().getAllColumns());
            builder.append(" FROM RACK_LEVEL T");
            builder.append(" LEFT JOIN RACK T0 ON T.\"RACK_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected RackLevel loadCurrentDeep(Cursor cursor, boolean lock) {
        RackLevel entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Rack rack = loadCurrentOther(daoSession.getRackDao(), cursor, offset);
         if(rack != null) {
            entity.setRack(rack);
        }

        return entity;    
    }

    public RackLevel loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<RackLevel> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<RackLevel> list = new ArrayList<RackLevel>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<RackLevel> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<RackLevel> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
