package com.tiendas3b.almacen.db.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "RECEIPT_COMMENTS".
 */
public class ReceiptComments {

    private Long tclave;
    private java.util.Date date;
    private Long pclave;
    private Integer odc;
    private Integer userId;
    private String comments;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ReceiptComments() {
    }

    public ReceiptComments(Long tclave, java.util.Date date, Long pclave, Integer odc, Integer userId, String comments) {
        this.tclave = tclave;
        this.date = date;
        this.pclave = pclave;
        this.odc = odc;
        this.userId = userId;
        this.comments = comments;
    }

    public Long getTclave() {
        return tclave;
    }

    public void setTclave(Long tclave) {
        this.tclave = tclave;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Long getPclave() {
        return pclave;
    }

    public void setPclave(Long pclave) {
        this.pclave = pclave;
    }

    public Integer getOdc() {
        return odc;
    }

    public void setOdc(Integer odc) {
        this.odc = odc;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
