package com.tiendas3b.almacen.db.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "RECEIPT_EXPRESS_LOG".
 */
public class ReceiptExpressLog {

    private String idAlmacen;
    private Long idProveedor;
    private Integer odc;
    private String date;
    private String time;
    private Integer idOrden;
    private Integer idProcess;
    private String description;
    private String user;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ReceiptExpressLog() {
    }

    public ReceiptExpressLog(String idAlmacen, Long idProveedor, Integer odc, String date, String time, Integer idOrden, Integer idProcess, String description, String user) {
        this.idAlmacen = idAlmacen;
        this.idProveedor = idProveedor;
        this.odc = odc;
        this.date = date;
        this.time = time;
        this.idOrden = idOrden;
        this.idProcess = idProcess;
        this.description = description;
        this.user = user;
    }

    public String getIdAlmacen() {
        return idAlmacen;
    }

    public void setIdAlmacen(String idAlmacen) {
        this.idAlmacen = idAlmacen;
    }

    public Long getIdProveedor() {
        return idProveedor;
    }

    public void setIdProveedor(Long idProveedor) {
        this.idProveedor = idProveedor;
    }

    public Integer getOdc() {
        return odc;
    }

    public void setOdc(Integer odc) {
        this.odc = odc;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public Integer getIdOrden() {
        return idOrden;
    }

    public void setIdOrden(Integer idOrden) {
        this.idOrden = idOrden;
    }

    public Integer getIdProcess() {
        return idProcess;
    }

    public void setIdProcess(Integer idProcess) {
        this.idProcess = idProcess;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
