package com.tiendas3b.almacen.db.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import com.tiendas3b.almacen.db.dao.TruckPackage;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TRUCK_PACKAGE".
*/
public class TruckPackageDao extends AbstractDao<TruckPackage, Long> {

    public static final String TABLENAME = "TRUCK_PACKAGE";

    /**
     * Properties of entity TruckPackage.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Status = new Property(1, Integer.class, "status", false, "STATUS");
        public final static Property TruckId = new Property(2, long.class, "truckId", false, "TRUCK_ID");
        public final static Property PackageId = new Property(3, long.class, "packageId", false, "PACKAGE_ID");
    };

    private DaoSession daoSession;


    public TruckPackageDao(DaoConfig config) {
        super(config);
    }
    
    public TruckPackageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TRUCK_PACKAGE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"STATUS\" INTEGER," + // 1: status
                "\"TRUCK_ID\" INTEGER NOT NULL ," + // 2: truckId
                "\"PACKAGE_ID\" INTEGER NOT NULL );"); // 3: packageId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TRUCK_PACKAGE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TruckPackage entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer status = entity.getStatus();
        if (status != null) {
            stmt.bindLong(2, status);
        }
        stmt.bindLong(3, entity.getTruckId());
        stmt.bindLong(4, entity.getPackageId());
    }

    @Override
    protected void attachEntity(TruckPackage entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TruckPackage readEntity(Cursor cursor, int offset) {
        TruckPackage entity = new TruckPackage( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // status
            cursor.getLong(offset + 2), // truckId
            cursor.getLong(offset + 3) // packageId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TruckPackage entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setStatus(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setTruckId(cursor.getLong(offset + 2));
        entity.setPackageId(cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TruckPackage entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TruckPackage entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getEpackageTruckDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getEPackageDao().getAllColumns());
            builder.append(" FROM TRUCK_PACKAGE T");
            builder.append(" LEFT JOIN EPACKAGE_TRUCK T0 ON T.\"TRUCK_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN EPACKAGE T1 ON T.\"PACKAGE_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected TruckPackage loadCurrentDeep(Cursor cursor, boolean lock) {
        TruckPackage entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        EpackageTruck epackageTruck = loadCurrentOther(daoSession.getEpackageTruckDao(), cursor, offset);
         if(epackageTruck != null) {
            entity.setEpackageTruck(epackageTruck);
        }
        offset += daoSession.getEpackageTruckDao().getAllColumns().length;

        EPackage epackage = loadCurrentOther(daoSession.getEPackageDao(), cursor, offset);
         if(epackage != null) {
            entity.setEpackage(epackage);
        }

        return entity;    
    }

    public TruckPackage loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<TruckPackage> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<TruckPackage> list = new ArrayList<TruckPackage>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<TruckPackage> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<TruckPackage> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
